import { Container, Header } from "@/shared/components";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by create next app',
};

export default function CheckoutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen bg-[#F4F1EE]">
        <Container>
            <Header hasButtonCart={false} hasSearch={false} />
            {children}
        </Container>
    </div>
  );
}
